LikeLion-team10/Mat-ZIP

src/main/java/site/matzip/base/domain/BaseEntity.java, src/main/java/site/matzip/comment/domain/Comment.java, src/main/resources/templates/map/map.html
- 마커 클릭시 이벤트 처리
- 식당 이름, 주소, 전화번호 출력
- 지도의 오른쪽 상단에 출력
- `맛집으로 등록` 버튼 추가
=> 마커 클릭 시, 식당 정보 가져오기

Dockerfile, build.gradle, src/main/resources/application-prod.yml
=> H2 JDBC 드라이버 의존성 추가

src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/domain/Matzip.java, src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java, src/main/java/site/matzip/matzip/dto/MatzipListDTO.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/resources/templates/map/map.html, src/main/resources/templates/matzip/list.html
- 맛집 리스트를 나만의 맛집 지도에 표시
- 마커 클릭 시, 식당 상세 정보, 큰지도 보기, 길찾기, 리뷰 등록 표시
- 마커 이미지 변경
- `map.html` 지도 크기 수정
- 인포윈도우 크기 수정
=> 맛집으로 등록한 정보들을 나만의 맛집 지도에 표시

src/main/resources/templates/map/map.html, src/main/resources/templates/usr/member/login.html
- 로그인상태와 비로그인 상태에 따라 버튼 다르게 표출
=> 비로그인 상태 맛집등록 요청시 로그인 유도

build.gradle, src/main/java/site/matzip/config/S3Config.java, src/main/java/site/matzip/image/domain/ReviewImage.java, src/main/java/site/matzip/image/repository/ReviewImageRepository.java, src/main/java/site/matzip/image/service/ReviewImageService.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/review/domain/Review.java, src/main/java/site/matzip/review/dto/ReviewCreationDTO.java, src/main/resources/application.yml, src/main/resources/templates/review/create.html
- S3 연결 완료
- 업로드 이미지 미리보기 기능 추가
- 업로드 이미지 최대 5개까지 허용
- 업로드 Service로직 적용
- Body로 전달되는 DTO를 ModelAttribute로 받도록 수정
=> 사진 업로드를위한 S3 연결

src/main/java/site/matzip/config/oauth/PrincipalOAuth2UserService.java, src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/member/domain/Member.java, src/main/java/site/matzip/member/dto/MemberInfoDTO.java, src/main/java/site/matzip/member/dto/NicknameUpdateDTO.java, src/main/java/site/matzip/member/repository/MemberRepository.java, src/main/java/site/matzip/member/service/MemberService.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/resources/static/resource/tabmenu.css, src/main/resources/templates/common/fragments/header.html, src/main/resources/templates/usr/member/myPage.html, src/main/resources/templates/usr/member/myPage/modifyNickname.html
- 닉네임 변경 기능 구현
- 마이 페이지 추가
- 닉네임 변경 페이지 추가
1. 마이 페이지
2. 닉네임 변경 페이지
3. 변경된 닉네임
=> 닉네임 변경 기능 구현

src/main/java/site/matzip/matzip/dto/MatzipInfoDTO.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/resources/templates/map/map.html, src/main/resources/templates/review/add.html
=> Matzip 엔티티 대신 DTO를 사용해 뷰로 데이터 전달

src/main/resources/templates/common/fragments/header.html
=> layout 디자인 변경 V1

src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/service/ReviewService.java
=> fix: import 추가, 메소드명 변경

src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/application.yml, src/main/resources/templates/matzip/list.html, src/main/resources/templates/matzip/mylist.html
=> 리스트 레이아웃 추가

src/main/java/site/matzip/map/MapController.java, src/main/resources/templates/matzip/list.html
- 메인에 리스트 출력하게 매핑
- 지도 영역 밖 누르면 리뷰리스트 함께 사라짐
=> 마커 클릭시 리뷰 리스트 출력

src/main/java/site/matzip/base/appConfig/AppConfig.java, src/main/java/site/matzip/image/domain/ProfileImage.java, src/main/java/site/matzip/image/repository/ProfileImageRepository.java, src/main/java/site/matzip/image/service/ProfileImageService.java, src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/member/domain/Member.java, src/main/java/site/matzip/member/dto/MemberInfoDTO.java, src/main/resources/application.yml, src/main/resources/templates/usr/member/myPage.html, src/main/resources/templates/usr/member/myPage/modifyProfileImage.html
- 프로필 이미지 변경 기능 구현
- 프로필 이미지 변경 페이지 추가
- AppConfig에 defaultProfileImageUrl 추가
- 프로필 이미지 변경 시 기존 파일에 덮어쓰기 되도록 UUID 제거
- 마이 페이지 본인이 작성한 리뷰 리스트 기능 구현
1. 마이 페이지(프로필 변경 전 기본 프로필 이미지)
2. 프로필 변경 페이지(변경 할 프로필 이미지 선택)
3. 마이 페이지(변경 된 프로필 이미지)
=> 프로필 이미지 변경

src/main/java/site/matzip/image/domain/ReviewImage.java, src/main/java/site/matzip/image/service/ReviewImageService.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/domain/Matzip.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/java/site/matzip/member/domain/Member.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/domain/Review.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/application.yml, src/main/resources/templates/review/createDev.html
- S3 보안설정 수정
- ReviewImage 로직 수정&적용
- ReviewImage DB에 저장
- view 상세보기 누락 수정
- createDev.html을 리뷰 등록 form으로가게 수정
- S3 ReviewImage 폴더 생성 후 관리
- S3 저장되는 naming 정책 수정
** 1. DB저장 확인
=> S3 보안설정 수정과 ReviewImage 로직 수정&적용

src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/dto/ReviewListDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/list.html, src/main/resources/templates/review/detail.html
- 리뷰에 저장된 별점에 따라 별점 표시되면서 출력⭐️
=> 리뷰 상세페이지 UI 1차 적용

src/main/java/site/matzip/image/domain/ReviewImage.java, src/main/java/site/matzip/image/service/ReviewImageService.java
- S3 리뷰 이미지 폴더 생성
- 업로드 이미지 업데이트를 위해 prefix 수정
=> S3 이미지 naming 정책 수정

src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/domain/Matzip.java, src/main/java/site/matzip/matzip/dto/MatzipListDTO.java, src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java, src/main/java/site/matzip/matzip/repository/MatzipRepository.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/repository/ReviewRepository.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/create.html, src/main/resources/templates/matzip/list.html, src/main/resources/templates/matzip/mylist.html, src/main/resources/templates/review/createDev.html
- mylist에서는 내가 작성한 리뷰만 보이게 구현
- list에서는 전체 리뷰 확인 가능하게 구현
- 본인이 등록한 맛집이 아닐경우 설명 평점란 안보이게 구현
- 지도 기본 레벨 조절해서 보다 넓은 영역 표시
- 컨트롤러 매핑 및 리다이렉트 수정
-  리스트 페이지 내 마커 클러스터러 적용
- 나만의 리스트와 전체 리스트 통합, 버튼으로 호출하는 방식
- 줌컨트롤러, 위성지도 추가하고 placeInfo 위치 조정.
- infoWindow 지도 영역 밖 누르면 사라짐
- 맛집 등록시 리스트로 이동할지 물어서 추가 등록 가능
- 등록창에서도 리뷰 보이게 구현....?
- infowindow에 들어갈 내용 추가
- 전체, 나의 맛지도에 캐싱 처리해서 새로 등록하기 전까지는 캐시에서 불러오기
- 토스트 메시지 예쁘게 만들기
- 검색기능 구현
테스트 유저 로그인 -> list
테스트 유저 로그인 -> mylist
OAuth2 유저 로그인 -> mylist
- 본인이 등록한 맛집이 아닐경우 설명 평점란 안보이게 구현
- 지도 기본 레벨 조정해서 보다 넓은 지역 표시
- 마커 클러스터러 적용 및 전체 리스트
- 나만의 지도
- 메인 페이지에 버튼 만들고 mylist, list 통합. (버튼에 스피너 적용)
- 위성지도 및 줌 컨트롤러 추가하고 placeInfo 위치 조정.
(좌우 바꾸는거 의견 받아서 수정가능)
- 맛집 등록시 리스트 or 추가등록 선택 가능
- 리스트 우측 하단에 맛집 등록 버튼 추가
=> 나의 맛집지도 만들기

src/main/java/site/matzip/review/controller/ReviewController.java
=> merge 충돌 이슈 해결

src/main/java/site/matzip/comment/dto/CommentInfoDTO.java
=> Builder 제거

src/main/java/site/matzip/comment/dto/CommentInfoDTO.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/dto/ReviewListDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/list.html, src/main/resources/templates/matzip/mylist.html, src/main/resources/templates/review/detail.html
- 리뷰 리스트 작성자 프로필 이미지 가져오기
- 리뷰 상세페이지 작성자 프로필 이미지 가져오기
- 댓글 작성자 프로필 이미지 가져오기
- ReviewDetailDTO, CommentInfoDTO `@Builder`를 사용하여 생성
1. 리뷰 리스트
2. 리뷰 상세 페이지
=> 리뷰, 댓글 프로필 이미지

src/main/java/site/matzip/MatzipApplication.java, src/main/java/site/matzip/badge/domain/Badge.java, src/main/java/site/matzip/badge/domain/MemberBadge.java, src/main/java/site/matzip/badge/repository/BadgeRepository.java, src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java, src/main/java/site/matzip/badge/service/MemberBadgeService.java, src/main/java/site/matzip/comment/repository/CommentRepository.java, src/main/java/site/matzip/matzip/domain/MatzipMember.java, src/main/java/site/matzip/matzip/repository/MatzipMemberRepository.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/java/site/matzip/member/domain/Member.java, src/main/java/site/matzip/member/repository/MemberRepository.java, src/main/java/site/matzip/review/repository/ReviewRepository.java, src/main/java/site/matzip/review/service/ReviewService.java
- 회원이 등록한 Matzip 개수로 뱃지를 부여하는 Service Schedule 생성
- 회원이 등록한 Comment 개수로 뱃지를 부여하는 Service Schedule 생성
- 회원이 등록한 Review 개수로 뱃지를 부여하는 Service Schedule 생성
- 내 정보 페이지에서 뱃지를 출력하도록 수정
=> 뱃지 갱신 Scheduling Service 구현 #56

src/main/java/site/matzip/badge/domain/BadgeType.java, src/main/java/site/matzip/badge/repository/MemberBadgeRepository.java, src/main/java/site/matzip/badge/service/MemberBadgeService.java, src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/member/dto/MemberInfoDTO.java, src/main/resources/templates/usr/member/myPage.html
- 마이페이지 출력 Dto 수정
- 마이페이지 view 수정
- fetch join으로 한번에 가져오도록 쿼리 수정
- 마이페이지 출력 로직 수정
- 좋아요, 친구 수 관련한 뱃지 추가
- 뱃지 수여 기준 정하기 (현재 11개 이상부터 뱃지 수여)
=> 마이페이지 뱃지 출력

src/main/java/site/matzip/MatzipApplication.java, src/main/java/site/matzip/badge/service/MemberBadgeService.java, src/main/java/site/matzip/logging/LoggingAspect.java
- AOP 적용, 모든 Cotroller 메서드 에서 Logging
- Scheduled 1분마다 발생하도록 변경
=> Controller 메서드에 로깅 AOP 적용

src/main/java/site/matzip/member/domain/Member.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/domain/Heart.java, src/main/java/site/matzip/review/domain/Review.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/repository/HeartRepository.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/review/detail.html
- 리뷰의 좋아요 기능 추가
- 리뷰의 좋아요 기능 비동기로 처리하도록 ajax 사용
- 리뷰 페이지 이미지 출력
- 좋아요 뱃지 출력
=> 리뷰 좋아요 기능 추가

src/main/java/site/matzip/comment/controller/CommentController.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/domain/Review.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/review/add.html, src/main/resources/templates/review/detail.html
=> Review 수정 / 삭제

src/main/java/site/matzip/badge/domain/BadgeType.java, src/main/java/site/matzip/badge/service/MemberBadgeService.java, src/main/java/site/matzip/comment/controller/CommentController.java, src/main/java/site/matzip/friend/repository/FriendRepository.java, src/main/java/site/matzip/image/domain/ReviewImage.java, src/main/java/site/matzip/member/repository/MemberRepository.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/domain/Review.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/repository/ReviewRepository.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/review/add.html, src/main/resources/templates/review/detail.html
=> 친구, 좋아요 뱃지 추가 & 리뷰 페이지 뱃지 띄워주도록 수정

src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/java/site/matzip/review/dto/ReviewListDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/list.html
=> 리뷰 리스트에 맛집수 친구수 리뷰수 출력

src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/java/site/matzip/notification/controller/NotificationController.java
=> incompatible types 문제 해결

src/main/java/site/matzip/image/service/ReviewImageService.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/dto/ReviewCreationDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/review/add.html
=> Review 수정시 기존 이미지 출력 / 리뷰 이미지 수정

src/main/java/site/matzip/image/repository/ReviewImageRepository.java, src/main/java/site/matzip/image/service/ReviewImageService.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/dto/MatzipReviewDTO.java, src/main/java/site/matzip/review/controller/ReviewController.java
- 리뷰 이미지 수정 시 S3에 저장되어있는 이미지 갱신되도록 수정
- 리뷰 이미지 삭제 시 S3에 저장되어있는 이미지 삭제되도록 수정
=> S3 리뷰 이미지 삭제 기능 추가

src/main/resources/static/common/common.css, src/main/resources/templates/error/400.html, src/main/resources/templates/error/401.html, src/main/resources/templates/error/403.html, src/main/resources/templates/error/404.html, src/main/resources/templates/error/500.html
=> 폰트 변경 & 에러 페이지 추가

src/main/java/site/matzip/review/dto/ReviewListDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/list.html
=> 리뷰리스트에 업로드한 사진보여주기

src/main/java/site/matzip/base/exception/GlobalExceptionHandler.java, src/main/java/site/matzip/base/exception/UnauthorizedException.java, src/main/java/site/matzip/friend/entity/Friend.java, src/main/java/site/matzip/friend/repository/FriendRepository.java, src/main/java/site/matzip/friend/service/FriendService.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/member/service/MemberService.java, src/main/resources/templates/common/fragments/header.html, src/main/resources/templates/matzip/create.html, src/main/resources/templates/matzip/list.html
- 비로그인시에 서버에 요청 안보냄
- 새로고침시에 현재 리스트 상태 기억했다가 다시 불러옴
- 친구 맛집지도 요청시 친구인지 확인
- 레이아웃 수정
=> 비로그인시 맛집리스트 요청 핸들링

src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/domain/MatzipMember.java, src/main/java/site/matzip/matzip/dto/MatzipModifyDTO.java, src/main/java/site/matzip/matzip/service/MatzipService.java, src/main/resources/templates/matzip/create.html, src/main/resources/templates/matzip/list.html
=> 맛집 update-> modify

src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/review/dto/MyReviewDTO.java, src/main/resources/static/resource/tabmenu.css, src/main/resources/templates/common/fragments/header.html, src/main/resources/templates/common/layout/defaultLayout.html, src/main/resources/templates/matzip/list.html, src/main/resources/templates/usr/friend/requestList.html, src/main/resources/templates/usr/member/myPage.html, src/main/resources/templates/usr/member/myPage/friend.html, src/main/resources/templates/usr/member/myPage/matzip.html, src/main/resources/templates/usr/member/myPage/point.html, src/main/resources/templates/usr/member/myPage/review.html, src/main/resources/templates/usr/notification/list.html, src/main/resources/templates/usr/notification/reviewList.html
=> 마이 페이지 디자인 수정

src/main/java/site/matzip/base/exception/GlobalExceptionHandler.java, src/main/java/site/matzip/base/exception/UnauthorizedException.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java, src/main/java/site/matzip/review/service/ReviewService.java, src/main/resources/templates/matzip/list.html, src/main/resources/templates/review/create.html
- 맛집 리뷰 동시에 등록 안되던거 수정
- 전화번호 제외하고는 입력값 오류 날 확률적어서 전화번호로 멘트 수정 => 전화번호 없으면 등록 못함
- 부다스밸리처럼 1688-1111 이런식으로 네자리-네자리 패턴 추가
=> 맛집 리뷰 동시에 작성 안되던 문제 해결

src/main/java/site/matzip/friend/controller/FriendController.java, src/main/java/site/matzip/friendRequest/controller/FriendRequestController.java, src/main/java/site/matzip/home/HomeController.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/notification/controller/NotificationController.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/resources/templates/common/fragments/header.html
=> rq -> PrincipalDetails 수정

src/main/java/site/matzip/comment/dto/CommentInfoDTO.java, src/main/java/site/matzip/friend/dto/FriendDTO.java, src/main/java/site/matzip/friend/dto/FriendDetailDTO.java, src/main/java/site/matzip/friendRequest/dto/FriendRequestDTO.java, src/main/java/site/matzip/home/HomeController.java, src/main/java/site/matzip/matzip/dto/MatzipCreationDTO.java, src/main/java/site/matzip/matzip/dto/MatzipInfoDTO.java, src/main/java/site/matzip/matzip/dto/MatzipListDTO.java, src/main/java/site/matzip/matzip/dto/MatzipModifyDTO.java, src/main/java/site/matzip/matzip/dto/MatzipRankDTO.java, src/main/java/site/matzip/matzip/dto/MatzipReviewDTO.java, src/main/java/site/matzip/matzip/dto/MatzipReviewListDTO.java, src/main/java/site/matzip/member/dto/MemberInfoCntDTO.java, src/main/java/site/matzip/member/dto/MemberInfoDTO.java, src/main/java/site/matzip/member/dto/MemberPointDTO.java, src/main/java/site/matzip/member/dto/MemberProfileDTO.java, src/main/java/site/matzip/member/dto/MemberRankDTO.java, src/main/java/site/matzip/member/dto/MemberRankInfoDTO.java, src/main/java/site/matzip/member/dto/NicknameUpdateDTO.java, src/main/java/site/matzip/notification/dto/NotificationDTO.java, src/main/java/site/matzip/review/dto/MyReviewDTO.java, src/main/java/site/matzip/review/dto/ReviewCreationDTO.java, src/main/java/site/matzip/review/dto/ReviewDetailDTO.java, src/main/java/site/matzip/review/dto/ReviewListDTO.java, src/main/resources/templates/common/fragments/header.html
=> DTO의 @Data 어노테이션 분리

src/main/java/site/matzip/config/SecurityConfig.java, src/main/java/site/matzip/home/HomeController.java, src/main/resources/templates/matzip/list.html, src/main/resources/templates/usr/member/myPage.html
- 친구 지도 문구, 평점 표시 방식 변경
- 인포윈도우에 평균 별점 표시 추가
=> 맛집 지도 인포윈도우에 평균점수 표시 및 친구페이지 view 수정

src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/resources/templates/matzip/list.html
- 수정 삭제 버튼 위치 및 크기 조정 (이름 긴 식당에는 적용 안됨 여기까지..)
=> 수정 삭제 버튼 크기 및 위치 조정

src/main/resources/templates/error/400.html, src/main/resources/templates/error/401.html, src/main/resources/templates/error/403.html, src/main/resources/templates/error/404.html, src/main/resources/templates/error/500.html, src/main/resources/templates/main/main.html, src/main/resources/templates/matzip/create.html, src/main/resources/templates/matzip/list.html, src/main/resources/templates/ranking/ranking.html, src/main/resources/templates/review/add.html, src/main/resources/templates/review/create.html, src/main/resources/templates/review/detail.html, src/main/resources/templates/usr/friend/list.html, src/main/resources/templates/usr/member/myPage/friend.html, src/main/resources/templates/usr/member/myPage/friendMap.html, src/main/resources/templates/usr/member/myPage/matzip.html, src/main/resources/templates/usr/member/myPage/modifyNickname.html, src/main/resources/templates/usr/member/myPage/modifyProfileImage.html, src/main/resources/templates/usr/member/myPage/point.html, src/main/resources/templates/usr/member/myPage/review.html, src/main/resources/templates/usr/member/myPage2.html
=> 에러 페이지 버튼 디자인 수정 & Title 변경

src/main/java/site/matzip/member/service/MemberService.java
=> 친구 삭제 관련 오류 수정

src/main/java/site/matzip/friend/dto/FriendDetailDTO.java, src/main/java/site/matzip/member/service/MemberService.java, src/main/resources/templates/usr/member/myPage/friend.html
=> 친구 맛지도 불러오기 오류 수정

src/main/java/site/matzip/config/auth/PrincipalDetails.java, src/main/java/site/matzip/home/HomeController.java, src/main/java/site/matzip/matzip/controller/MatzipController.java, src/main/java/site/matzip/member/controller/MemberController.java, src/main/java/site/matzip/notification/controller/NotificationController.java, src/main/java/site/matzip/review/controller/ReviewController.java, src/main/java/site/matzip/review/service/ReviewService.java, src/test/java/site/matzip/review/service/ReviewServiceTest.java
=> 조회수 쿠키 유저아이디 추가 / 메서드 통일
